### ISSUE TITLE
Feature request: more jump modes

### ISSUE THREAD

**Issue by ivanbarsukov** [wenfangdu/vscode-jump#10]
I recently transitioned to vscode-jump from using the EasyMotion plugin in neovim and I've been finding it immensely useful. However, I've noticed a couple of features that I miss and that could make coding experience even better:

- Jump to Char
- Jump to Line

Are there any plans to develop these features in the plugin?

**Comment by wenfangdu** [comment]
@ivanbarsukov Thanks for the request.
1. Jump to Char is actually very hard to implement since Jump uses two characters to locate the target, if implemented, the decorations would be covered by each other.
2. Jump to Line is already covered by Jump to Word, and I'd like to keep the API minimal so that users won't have to remember and choose.
