### ISSUE TITLE
Cyrillic words is not recognized for jumping

### ISSUE THREAD

**Issue by ivanbarsukov** [wenfangdu/vscode-jump#11]
![image](https://github.com/user-attachments/assets/eff40e1f-1eee-4ef4-a820-7e384dceecd4)
![image](https://github.com/user-attachments/assets/63fb5242-4452-4c7f-93d6-bf7bdb69709d)

**Comment by wenfangdu** [comment]
I don't think there's a good way to achieve this, since these characters are hard to tell if it's a word or just characters, like 树、树木、树木繁茂, that would require a database for all these combinations, and not everyone can agree with, since even dictionaries have updates too. With that said, I'm open for ideas.

**Comment by ivanbarsukov** [comment]
In cases of word separation, languages ​​using Latin and languages ​​using Cyrillic differ little. I proposed an implementation in PR by adding Cyrillic characters to the regular expression

**Comment by wenfangdu** [comment]
@ivanbarsukov Can you please paste the screenshot code here, so I can test.

**Comment by ivanbarsukov** [comment]
Sure, file with the code is here:

https://github.com/nextgis/qgis_molusce/blob/master/src%2Fmolusce%2Fmetadata.txt

**Comment by wenfangdu** [comment]
@ivanbarsukov Released in 0.8.0, please verify.

**Comment by wenfangdu** [comment]
@ivanbarsukov Released in 0.8.0, please verify that it's working as intended.

**Comment by ivanbarsukov** [comment]
Works great. Thank you!
